version: '3'

services: 
  mgmt1:
    image: mysql/mysql-cluster 
    command: ndb_mgmd
    container_name: mgmt1
    volumes: 
      - mgmt1:/var/lib/mysql
    networks: 
      mysql_cluster:
        ipv4_address: 192.168.0.2

  ndb1:
    image: mysql/mysql-cluster 
    command: ndbd
    container_name: ndb1
    volumes: 
      - ndb1:/var/lib/mysql
    networks:
      mysql_cluster:
        ipv4_address: 192.168.0.3
      

  ndb2:
    image: mysql/mysql-cluster 
    command: ndbd
    container_name: ndb2
    volumes: 
      - ndb2:/var/lib/mysql
    networks: 
      mysql_cluster:
        ipv4_address: 192.168.0.4

  server_node:
    image: mysql/mysql-cluster 
    command: mysqld
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=prasad
      - MYSQL_PASSWORD=prasad
      - MYSQL_DATABASE=prasad
    ports:
      - "3306:3306"
    container_name: mysql1
    volumes: 
      - servernode:/var/lib/mysql
    networks:
      mysql_cluster:
        ipv4_address: 192.168.0.10

  wordpress:
    image: wordpress
    restart: always
    ports: 
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: server_node
      WORDPRESS_DB_USER: prasad
      WORDPRESS_DB_PASSWORD: prasad
      WORDPRESS_DB_NAME: prasad 
    depends_on: 
      - mgmt1
      - ndb1
      - ndb2
      - server_node
    networks:
      mysql_cluster:
        ipv4_address: 192.168.0.11
    volumes:
      - wordpress_data:/var/www/html

volumes: 
  mgmt1:
  ndb1:
  ndb2:
  servernode:
  wordpress_data:

networks: 
  mysql_cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
 
      
